added scrape-meta and scrape for riverside pd
biglocalnews/clean-scraper pull request #57
Opened 2024-08-02 12:34 UTC by naumansharifwork

Hey fellows,
Created scraper for City of Riverside,
Below is the tree screenshot and meta json
i have made folder name as case numbers.
![image](https://github.com/user-attachments/assets/87164de3-e65f-47ec-9358-60ab00c5c20e)
[ca_river_side_pd.json](https://github.com/user-attachments/files/16470468/ca_river_side_pd.json)

2024-08-03 13:07 UTC, naumansharifwork commented
@zstumgoren @newsroomdev please review this PR as well i have formatted the json as it was mentioned in the discussion
[ca_river_side_pd.json](https://github.com/user-attachments/files/16480680/ca_river_side_pd.json)

2024-08-05 15:09 UTC, tarakc02 requested changes
@naumansharifwork, sorry i misesed this earlier, but filename/slug should be "riverside_pd" rather than "river_side_pd". otherwise i don't have any other changes, it looks good to me.

2024-08-09 02:50 UTC, tarakc02 requested changes

2024-08-09 11:47 UTC, naumansharifwork commented on clean/ca/riverside_pd.py
> +        folder_name = asset["case_number"]
@tarakc02 fixed

2024-08-09 13:18 UTC, tarakc02 approved these changes
looks good to me!

2024-08-10 07:02 UTC, naumansharifwork commented
Hey @zstumgoren please review this as well, Thanks

2024-08-13 21:26 UTC, newsroomdev requested changes

2024-08-13 21:26 UTC, newsroomdev commented on clean/ca/riverside_pd.py
> +                            "case_num": case_id,
small tweak to match spec
```suggestion
                            "case_id": case_id,
```

2024-08-13 21:26 UTC, newsroomdev commented on clean/ca/riverside_pd.py
> +    def scrape(self, throttle: int = 4, filter: str = "") -> List[Path]:
note: this will be deprecated in #82

2024-08-13 22:09 UTC, newsroomdev commented
This is looking very close to being done! Nice work. Two changes and this should be good to merge. Let me know when you'd like me to take another look, and thank you for your diligence as this codebase adds downstream dependencies

2024-08-14 07:00 UTC, naumansharifwork commented
Hey @newsroomdev Thanks for the review, the requested changes are done please check Thanks.

2024-08-15 20:29 UTC, newsroomdev commented on clean/ca/riverside_pd.py
> +    def scrape(self, throttle: int = 4, filter: str = "") -> List[Path]:
removed 👍

2024-08-15 20:29 UTC, newsroomdev commented on clean/ca/riverside_pd.py
> +                            "case_num": case_id,
fixed 👍

2024-08-15 20:45 UTC, newsroomdev approved these changes
This is looking good! Feel free to merge it in when you're ready

2024-08-19 18:32 UTC, merged